### PR TITLE
Fix panic on double close due to channel being copied

### LINKED ISSUE #119: interrupt of long run: panic bug
```
07:45:56 W http.go:667> Parsed non ok code 503 (HTTP/1.1 503)
07:45:56 W http.go:667> Parsed non ok code 503 (HTTP/1.1 503)
07:45:56 W http.go:667> Parsed non ok code 503 (HTTP/1.1 503)
07:45:56 W http.go:667> Parsed non ok code 503 (HTTP/1.1 503)
07:45:56 W http.go:667> Parsed non ok code 503 (HTTP/1.1 503)
07:48:33 I uihandler.go:426> UI: GET /fortio/?stop=Stop&runid=43 HTTP/1.1 216.239.45.130:55783 ()
07:48:33 C uihandler.go:153> Stop request from 216.239.45.130:55783 for 43
07:48:33 I periodic.go:499> T009 ended after 1h24m36.175139994s : 50762 calls. qps=10.000048973893362
07:48:33 I periodic.go:499> T005 ended after 1h24m36.175179648s : 50762 calls. qps=10.000048895775109
07:48:33 I periodic.go:499> T007 ended after 1h24m36.175199914s : 50762 calls. qps=10.000048855851155
07:48:33 I periodic.go:499> T006 ended after 1h24m36.17520971s : 50762 calls. qps=10.000048836553066
07:48:33 I periodic.go:499> T002 ended after 1h24m36.176164715s : 50762 calls. qps=10.000046955196641
07:48:33 I periodic.go:499> T008 ended after 1h24m36.176496053s : 50762 calls. qps=10.000046302462135
07:48:33 I periodic.go:499> T003 ended after 1h24m36.180292916s : 50762 calls. qps=10.000038822663623
07:48:33 I periodic.go:499> T000 ended after 1h24m36.181708568s : 50762 calls. qps=10.000036033840098
07:48:33 I periodic.go:499> T001 ended after 1h24m36.181749501s : 50762 calls. qps=10.000035953202428
07:48:33 I periodic.go:499> T004 ended after 1h24m36.184033277s : 50762 calls. qps=10.00003145418467
07:48:33 http: panic serving 172.10.234.41:51533: close of closed channel
goroutine 6673 [running]:
net/http.(*conn).serve.func1(0xc4202620a0)
        /usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0x8c0fc0, 0xc4205eeae0)
        /usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
istio.io/fortio/periodic.(*RunnerOptions).Abort(0xc42025a780)
        /home/ldemailly/go/src/istio.io/fortio/periodic/periodic.go:233 +0x62
istio.io/fortio/fhttp.RunHTTPTest(0xc420012380, 0xc420072410, 0x0, 0x0)
        /home/ldemailly/go/src/istio.io/fortio/fhttp/httprunner.go:156 +0xdf5
istio.io/fortio/ui.Handler(0xb93400, 0xc4200122a0, 0xc4200d4500)
        /home/ldemailly/go/src/istio.io/fortio/ui/uihandler.go:294 +0xc12
net/http.HandlerFunc.ServeHTTP(0x976648, 0xb93400, 0xc4200122a0, 0xc4200d4500)
        /usr/lib/go-1.8/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xbd1b60, 0xb93400, 0xc4200122a0, 0xc4200d4500)
        /usr/lib/go-1.8/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4202380b0, 0xb93400, 0xc4200122a0, 0xc4200d4500)
        /usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4202620a0, 0xb93c80, 0xc420672080)
        /usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
```

On page:
```
Up for 27h28m14.8s (since Wed Feb 7 02:55:42 2018).

1M 100qps ing-f2-f1 35.199.14.248/fortio2/fortio/fetch/echosrv1:8080/echo

Running load test... Results pending... 

Interrupt
Starting at 100 qps with 10 thread(s) [gomax 2] : exactly 1000000, 100000 calls each (total 1000000 + 0)
Ended after 1h24m36.184069079s : 507620 calls. qps=100
Sleep times : count 507620 avg 0.071686248 +/- 0.06425 min -2.920981178 max 0.099712334 sum 36389.3734
Aggregated Function Time : count 507620 avg 0.023398227 +/- 0.02961 min 7.4395e-05 max 3.02076883 sum 11877.4082
# range, mid point, percentile, count
>= 7.4395e-05 <= 0.001 , 0.000537198 , 0.00, 10
> 0.001 <= 0.002 , 0.0015 , 0.00, 8
> 0.002 <= 0.003 , 0.0025 , 0.02, 73
> 0.003 <= 0.004 , 0.0035 , 0.07, 265
> 0.004 <= 0.005 , 0.0045 , 0.12, 243
> 0.005 <= 0.006 , 0.0055 , 0.25, 659
> 0.006 <= 0.007 , 0.0065 , 0.39, 713
> 0.007 <= 0.008 , 0.0075 , 0.53, 710
> 0.008 <= 0.009 , 0.0085 , 0.93, 2028
> 0.009 <= 0.01 , 0.0095 , 2.05, 5688
> 0.01 <= 0.011 , 0.0105 , 4.30, 11449
> 0.011 <= 0.012 , 0.0115 , 7.85, 18020
> 0.012 <= 0.014 , 0.013 , 18.76, 55382
> 0.014 <= 0.016 , 0.015 , 33.19, 73246
> 0.016 <= 0.018 , 0.017 , 47.12, 70708
> 0.018 <= 0.02 , 0.019 , 57.92, 54796
> 0.02 <= 0.025 , 0.0225 , 76.14, 92513
> 0.025 <= 0.03 , 0.0275 , 85.62, 48098
> 0.03 <= 0.035 , 0.0325 , 90.28, 23693
> 0.035 <= 0.04 , 0.0375 , 92.90, 13265
> 0.04 <= 0.045 , 0.0425 , 94.45, 7904
> 0.045 <= 0.05 , 0.0475 , 95.56, 5623
> 0.05 <= 0.06 , 0.055 , 97.09, 7764
> 0.06 <= 0.07 , 0.065 , 98.02, 4691
> 0.07 <= 0.08 , 0.075 , 98.59, 2920
> 0.08 <= 0.09 , 0.085 , 98.96, 1889
> 0.09 <= 0.1 , 0.095 , 99.19, 1171
> 0.1 <= 0.12 , 0.11 , 99.44, 1266
> 0.12 <= 0.14 , 0.13 , 99.59, 769
> 0.14 <= 0.16 , 0.15 , 99.69, 498
> 0.16 <= 0.18 , 0.17 , 99.75, 279
> 0.18 <= 0.2 , 0.19 , 99.77, 134
> 0.2 <= 0.25 , 0.225 , 99.81, 183
> 0.25 <= 0.3 , 0.275 , 99.83, 92
> 0.3 <= 0.35 , 0.325 , 99.84, 80
> 0.35 <= 0.4 , 0.375 , 99.86, 56
> 0.4 <= 0.45 , 0.425 , 99.87, 53
> 0.45 <= 0.5 , 0.475 , 99.88, 82
> 0.5 <= 0.6 , 0.55 , 99.93, 239
> 0.6 <= 0.7 , 0.65 , 99.97, 221
> 0.7 <= 0.8 , 0.75 , 99.99, 111
> 0.8 <= 0.9 , 0.85 , 100.00, 12
> 0.9 <= 1 , 0.95 , 100.00, 1
> 1 <= 2 , 1.5 , 100.00, 9
> 3 <= 3.02077 , 3.01038 , 100.00, 6
# target 50% 0.0185332
# target 75% 0.0246867
# target 90% 0.0346953
# target 99% 0.0915867
# target 99.9% 0.538234
Code  -1 : 10 (0.0 %)
Code 200 : 501723 (98.8 %)
Code 503 : 5887 (1.2 %)
Response Header Sizes : count 507620 avg 164.01283 +/- 17.78 min 0 max 185 sum 83256194
Response Body/Total Sizes : count 507620 avg 166.43754 +/- 5.049 min 0 max 227 sum 84487022
```

### PR DESCRIPTION
**Pull request by ldemailly**
Make sure abort channel isn't copied
Encapsulate the Abort() and the lock (better granularity too)

Fixes #119

### CODE REVIEW

File: periodic/periodic.go [hunk 1]
```diff
@@ -70,6 +70,31 @@ func (r *RunnerOptions) MakeRunners(rr Runnable) {
 	}
 }
 
+// Aborter is the object controlling Abort() of the runs.
+type Aborter struct {
+	StopChan   chan struct{}
+	AbortMutex sync.Mutex
```
Comment (rkpagadala) [inline periodic/periodic.go]: Change  
AbortMutex sync.Mutex
to
sync.Mutex

Using anonymous fields

**Review by rkpagadala — APPROVED** [review]
otherwise lgtm

File: periodic/periodic.go (hunk 1 above)
Comment (ldemailly) [reply periodic/periodic.go]: you're right ! much better that way ! thanks !
