### PR TITLE
Tests for slice/array returned from jrpc calls as well as a cleaner shortcut: `jrpc.GetArray()`

### LINKED ISSUE #633: jrpc - make cleaner error message
I had the following error:

```
2022/10/24 16:21:15 deserialization error, code 404: invalid character '<' looking for beginning of value (raw reply: 54712: <!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"/><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/><meta...4327a12b80cac28c34f.js\"></script><script nonce=\"\">performance.mark('frontend_boot_js_done_time_seconds');</script></body></html>)
exit status 1
```

This was due to a bug on my end (wrong path to request). Yet I found the error confusing and it took me a while to get it. What would make it more clear/easier is a format like:

```
2022/10/24 16:21:15 deserialization error: invalid character '<' looking for beginning of value 
2022/10/24 16:21:15 request: HTTP code 404
2022/10/24 16:21:15 raw reply: 54712: <!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"/><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/><meta...4327a12b80cac28c34f.js\"></script><script nonce=\"\">performance.mark('frontend_boot_js_done_time_seconds');</script></body></html>
exit status 1
```

### PR DESCRIPTION
**Pull request by ldemailly**
Add tests for slice/array returned from jrpc calls as well as a cleaner shortcut/example of use: `jrpc.GetArray()`

Also fix #633 incidentally

### CODE REVIEW

File: jrpc/jrpc_test.go [hunk 1]
```diff
@@ -270,7 +270,7 @@ func TestJPRC(t *testing.T) {
 	if unwrap.Error() != expected {
 		t.Errorf("unwrapped error expected to be %q, got %v", expected, unwrap.Error())
 	}
-	expected = "deserialization error, code 747: " + expected + " (raw reply: {bad})"
+	expected = "non ok http result and deserialization error, code 747: " + expected + " (raw reply: {bad})"
```
Comment (wiardvanrij) [inline jrpc/jrpc_test.go:273]:
```suggestion
	expected = "non ok http result and deserialization error, code 747: " + expected + " - raw reply: {bad}"
```
Removing the `()` - personal nit

**Review by wiardvanrij — APPROVED** [review]
Awesome :D

File: jrpc/jrpc_test.go (hunk 1 above)
Comment (ldemailly) [reply jrpc/jrpc_test.go:273]: that's the test :) - and in general the reason it's in () is the raw reply isn't typically necessary to be looked at
