### PR TITLE
fix special grpc metadata handling

### LINKED ISSUE #700: Bug about handling grpc authority metadata
fortio version: 1.40.0
I run a fortio server with `fortio server -grpc-port=9001 -loglevel=debug` and locally with `fortio load -grpc -ping -n=5 -H="host:google.com" localhost:9001`.After running a client, the server prints:
```
16:52:04 I logger.go:150> Log level is now 0 Debug (was 2 Info)
16:52:04 V stats.go:528> Will use [50 75 90 99 99.9] for percentiles
16:52:04 Fortio 1.40.0 tcp-echo server listening on tcp [::]:8078
16:52:04 Fortio 1.40.0 udp-echo server listening on udp [::]:8078
16:52:04 Fortio 1.40.0 grpc 'ping' server listening on tcp [::]:9001
16:52:04 Fortio 1.40.0 https redirector server listening on tcp [::]:8081
16:52:04 Fortio 1.40.0 http-echo server listening on tcp [::]:8080
16:52:04 Data directory is /home/kevin
16:52:04 REST API on /fortio/rest/run, /fortio/rest/status, /fortio/rest/stop
UI started - visit:
http://localhost:8080/fortio/
(or any host/ip reachable on this server)
16:52:04 I fortio_main.go:297> Note: not using dynamic flag watching (use -config to set watch directory)
16:52:04 I fortio_main.go:305> All fortio 1.40.0 h1:jSDO/jGcyC/qTpMZZ84EZbn9BQawsWM9/RMQ9s6Cn3w= go1.19.2 amd64 linux servers started!
16:52:13 V pingsrv.go:48> Ping called {Seq:1 Ts:1675155133396903376 Payload: DelayNanos:0} (meta map[:authority:[localhost:9001] content-type:[application/grpc] user-agent:[grpc-go/1.52.1]])
16:52:13 V pingsrv.go:48> Ping called {Seq:0 Ts:1675155133396903376 Payload: DelayNanos:0} (meta map[:authority:[google.com] content-type:[application/grpc] user-agent:[fortio.org/fortio-1.40.0 grpc-go/1.52.1]])
16:52:13 V pingsrv.go:48> Ping called {Seq:0 Ts:1675155133396903376 Payload: DelayNanos:0} (meta map[:authority:[google.com] content-type:[application/grpc] user-agent:[fortio.org/fortio-1.40.0 grpc-go/1.52.1]])
16:52:13 V pingsrv.go:48> Ping called {Seq:1 Ts:1675155133396903376 Payload: DelayNanos:0} (meta map[:authority:[localhost:9001] content-type:[application/grpc] user-agent:[grpc-go/1.52.1]])
16:52:14 V pingsrv.go:48> Ping called {Seq:0 Ts:1675155133396903376 Payload: DelayNanos:0} (meta map[:authority:[google.com] content-type:[application/grpc] user-agent:[fortio.org/fortio-1.40.0 grpc-go/1.52.1]])
```
As we've seen, the metadata "authority" for some requests is not "google.com," but "localhost:9001",there's obviously something wrong here

### PR DESCRIPTION
**Pull request by ktalg**
fix https://github.com/fortio/fortio/issues/700

There is a bug in the current handling of special grpc metadata (user-agent,host): 
The MD itself is modified in the Dial method so that other threads cannot read the original MD while establishing a connection 

Modifications to the MD are now moved outside of the Dial and need to be called separately when the request is sent

### CODE REVIEW

**Comment by ldemailly** [comment]
Hi @ktalg how does the issue show up? (grpc run - missing headers in some? do you have a human visible repro?)

File: fgrpc/grpcrunner.go [hunk 1]
```diff
@@ -316,14 +316,26 @@ func grpcDestination(dest string) (parsedDest string) {
...
 	for k, v := range in {
 		switch k {
-		// Transfer these 2 and avoid having them duplicated in original MD
+		// Transfer these 2
 		case "user-agent":
-			delete(in, k)
 			out = append(out, grpc.WithUserAgent(v[0]))
 		case "host":
-			delete(in, k)
 			out = append(out, grpc.WithAuthority(v[0]))
```
Comment (ldemailly) [inline fgrpc/grpcrunner.go:328]: is this only these 2 that were missing on next dial because removed or something else?

File: fgrpc/grpcrunner.go [hunk 2]
```diff
@@ -316,14 +316,26 @@ func grpcDestination(dest string) (parsedDest string) {
 func extractDialOptions(in metadata.MD) (out []grpc.DialOption) {
```
Comment (ldemailly) [inline fgrpc/grpcrunner.go]: seems maybe this should just return 2 things, the dial options and the filtered MD? (avoiding the separate sanitize() or at least rename sanitize for something clearer like filterMetaData() but it seems odd the 2 can't be combined)

File: fgrpc/grpcrunner.go (hunk 1 above)
Comment (ktalg) [reply fgrpc/grpcrunner.go:328]: > is this only these 2 that were missing on next dial because removed or something else?

Yes, I don't think it's a good idea to modify metadata in Dial

File: fgrpc/grpcrunner.go (hunk 2 above)
Comment (ktalg) [reply fgrpc/grpcrunner.go]: If I understand this correctly, then in terms of function naming, the "Dial" used for the connection should not contain side effects

Comment (ldemailly) [reply fgrpc/grpcrunner.go]: ic the issue is the one time setup is here but somehow the grpc meta data keeps getting set in the context each time, it's not very efficient to keep "sanitizing" it though even if we keep assigning it

File: fgrpc/grpcrunner_test.go [hunk 3]
```diff
@@ -546,7 +557,7 @@ func Test_extractDialOptions(t *testing.T) {
 			if !reflect.DeepEqual(len(gotOut), tt.wantOutLen) {
 				t.Errorf("extractDialOptions() = %v, want %v", len(gotOut), tt.wantOutLen)
 			}
-			if !reflect.DeepEqual(tt.args.in, tt.wantMD) {
+			if !reflect.DeepEqual(sanitize(tt.args.in), tt.wantMD) {
```
Comment (ldemailly) [inline fgrpc/grpcrunner_test.go]: using the function that ends up being tested in the test isn't super great... it's tautological

Comment (ldemailly) [reply fgrpc/grpcrunner_test.go]: I wanted to see the test fail first and pass with the changes in the main but the test doesn't fail, it doesn't compile without the new code

Comment (ldemailly) [reply fgrpc/grpcrunner_test.go]: but removing sanitize (because the old extractDialOptions mutates tt.args.in) "works" for that purpose

**Comment by ldemailly** [comment]
I'm testing a variant with setting things only once

File: fgrpc/grpcrunner.go (hunk 2 above)
Comment (ldemailly) [reply fgrpc/grpcrunner.go]: @ktalg please look at https://github.com/fortio/fortio/pull/701/commits/416e9d5e0a3781a95efa31e1aede251ff6bdd0cd for what I meant

(tried to push to your branch but failed so it's in 701)

Comment (ktalg) [reply fgrpc/grpcrunner.go]: > ic the issue is the one time setup is here but somehow the grpc meta data keeps getting set in the context each time, it's not very efficient to keep "sanitizing" it though even if we keep assigning it

I'm aware of this, and it seems like a much bigger change would be needed to handle it well, and I have to be honest and say I can't assess whether such a change would be worth it 🥲 It involves a lot of design considerations...

File: fgrpc/grpcrunner_test.go (hunk 3 above)
Comment (ktalg) [reply fgrpc/grpcrunner_test.go]: > using the function that ends up being tested in the test isn't super great... it's tautological

thanks a lot for the suggestion, but what do you mean by "the function that ends up being tested"? This test function just reuses the test case to test "extractDialOptions" and "sanitize" I didn't use these 2 functions to create the expected "want result"

File: fgrpc/grpcrunner.go (hunk 2 above)
Comment (ldemailly) [reply fgrpc/grpcrunner.go]: well I did the change, can you review it in #701

Comment (ldemailly) [reply fgrpc/grpcrunner.go]: I will try again to push it to your fork in a bit

Comment (ldemailly) [reply fgrpc/grpcrunner.go]: @ktalg it worked this time, PTAL at https://github.com/fortio/fortio/pull/697/commits/d906484c90afbcc25ed1d17aa2010660916c5402
and if you think it makes sense we can merge this and put it in 1.40.1

File: fgrpc/grpcrunner_test.go (hunk 3 above)
Comment (ldemailly) [reply fgrpc/grpcrunner_test.go]: ic, yes now that it's one function it's clearer I think

**Review by ldemailly — APPROVED** [review]
(though I'm kinda approving my own changes too so KT ptal)

File: fgrpc/grpcrunner.go (hunk 2 above)
Comment (ktalg) [reply fgrpc/grpcrunner.go]: > @ktalg it worked this time, PTAL at [d906484](https://github.com/fortio/fortio/commit/d906484c90afbcc25ed1d17aa2010660916c5402) and if you think it makes sense we can merge this and put it in 1.40.1

it makes sense, thanks a lot!

**Comment by ktalg** [comment]
@ldemailly  and how about improving the name of `extractDialOptions`, because it does two things

**Comment by ldemailly** [comment]
> @ldemailly  and how about improving the name of `extractDialOptions`, because it does two things

yes that's a good point. will change it. code wise though, thoughts/ok?

**Comment by ldemailly** [comment]
oh you did already, cool

**Comment by ktalg** [comment]
> > @ldemailly  and how about improving the name of `extractDialOptions`, because it does two things
> 
> yes that's a good point. will change it. code wise though, thoughts/ok?

I think our changes are good enough, there's nothing more to suggest! 

But I seem to have violated 'DRY' in some places, and I think I should avoid these if there is a big refactoring in the future

**Comment by ldemailly** [comment]
thx we can further cleanup in #681 (repeat in tests is somewhat fine btw)
