### PR TITLE
Multiple improvements/fixes

### LINKED ISSUE #172: unexpected init with empty url when using -H
$ fortio curl -H Host:httpbin  http://35.193.254.22/headers
17:58:00 E http.go:100> unexpected init with empty url

### PR DESCRIPTION
**Pull request by ldemailly**
- add both link to UI and Json data from run results and browse UI And a back to top link

- Fix #172 (error logged when using -H)

- Initial version of #170  &close option for echo server

- Build with both go1.8 and 1.10; put 1.10 binaries in docker images/release

- Add StdClient option for the web UI runs

- Misc cleanups to front page (grpc secure option)

- Add socket use cout (#165)

- don't consider early EOF or other an error (fix 50% errors for some call client closes - like /fortio/fetch/ does)

- Reminder of fix for #168 show grpc result codes in UI/text

### CODE REVIEW

File: fhttp/http.go [hunk 1]
```diff
@@ -345,7 +356,7 @@ type FastClient struct {
 
 // Close cleans up any resources used by FastClient
 func (c *FastClient) Close() {
-	log.Debugf("Closing %+v", c)
+	log.Debugf("Closing %p %s", c, c.url)
```
Comment (ldemailly) [inline fhttp/http.go]: fixes log flood where the buffer was logged in debug mode

File: fhttp/http.go [hunk 2]
```diff
@@ -1102,6 +1113,9 @@ func EchoHandler(w http.ResponseWriter, r *http.Request) {
 			}
 		}
 	}
+	if r.FormValue("close") != "" {
+		w.Header().Set("Connection", "close")
```
Comment (ldemailly) [inline fhttp/http.go]: this does close the connection, not just sets the header

File: ui/templates/browse.html [hunk 3]
```diff
@@ -128,5 +128,6 @@ <h1>Φορτίο (fortio) v{{.Version}}{{.Extra}}</h1>
 fortio_load(files.value)
 </script>
 {{end}}
+<p>Go to <a href='./'>Top</a>.</p>
```
Comment (asadali) [inline ui/templates/browse.html:131]: this link resolves to `<host-path>:8080/fortio/`

so, if used from the browse page, the link redirects to the fortio landing page rather than the top of the `/fortio/browse/` page.

if that is intentional, then rewording this to `Go Back` makes more sense.

else replace `href='./'` with `href='#'`

suggetion: the heading `<h1>Φορτίο (fortio) v{{.Version}}{{.Extra}}</h1>` can be enhanced as a link to the landing page

File: fhttp/httprunner.go [hunk 4]
```diff
@@ -142,6 +143,7 @@ func RunHTTPTest(o *HTTPRunnerOptions) (*HTTPRunnerResults, error) {
 	}
 	sort.Ints(keys)
 	totalCount := float64(total.DurationHistogram.Count)
+	fmt.Fprintf(out, "Sockets used: %d (for perfect keepalive, would be %d)\n", total.SocketCount, r.Options().NumThreads)
```
Comment (asadali) [inline fhttp/httprunner.go:146]: +1

**Review by asadali — COMMENTED** [review]
- the build v6 go1.10/go1.8 changes look good.
- minor change on "Go to Top" functionality.

File: ui/templates/browse.html (hunk 3 above)
Comment (ldemailly) [reply ui/templates/browse.html:131]: it’s a bit subtle but there are really more than 1 top depending on report only vs full server so I left the label ambiguous rather than add more variables and mode

File: fhttp/http.go [hunk 5]
```diff
@@ -683,14 +703,22 @@ func (c *FastClient) readResponse(conn *net.TCPConn) {
...
 			if err != nil {
+				if reusedSocket && c.size == 0 {
+					// Ok for reused socket to be dead once (close by server)
+					log.Infof("Closing dead socket %v (err %v at first read)", *conn, err)
+					c.errorCount++
+					err = conn.Close() // close the previous one
+					if err != nil {
+						log.Warnf("Error closing dead socket %v: %v", *conn, err)
+					}
+					c.code = -2 // special "retry once" code
```
Comment (douglas-reid) [inline fhttp/http.go]: worth making the special code a const ?

**Review by douglas-reid — COMMENTED** [review]
LGTM

**Review by douglas-reid — APPROVED** [review]
